/* eslint-disable @typescript-eslint/no-explicit-any */
import localize from './localize';
import { BodymiscaleCardConfig, RenderAttributeData, RenderBodyData } from './types';

let compute = {
  convertkgtolb: (v: any) => Math.round(Number(v) * 2.20462 * 10) / 10,
};

export const states = {
  status: {
    order: 1,
    key: 'state',
    icon: 'mdi:scale-bathroom',
  },
  problem: {
    order: 2,
    key: 'problem',
    icon: 'mdi:alert',
  },
  last_measurement_time: {
    order: 3,
    key: 'last_measurement_time',
    icon: 'mdi:calendar-clock',
  },
};

export const attributes_kg: Record<string, RenderAttributeData> = {
  weight: {
    key: 'weight',
    label: localize(`attributes.${'weight: '}`),
    order: 1,
    show: true,
    unit: ' kg',
  },
  impedance: {
    key: 'impedance',
    label: localize(`attributes.${'impedance: '}`),
    unit: ' ohm',
    impedance_required: true,
    dual_impedance_required: false,
    order: 2,
    show: true,
  },
  impedance_low: {
    order: 2,
    key: 'impedance_low',
    label: localize(`attributes.${'impedance_low: '}`),
    unit: ' ohm',
  impedance_required: true,
    dual_impedance_required: true,
    show: true,
  },
  impedance_high: {
    order: 3,
    key: 'impedance_high',
    label: localize(`attributes.${'impedance_high: '}`),
    unit: ' ohm',
    impedance_required: true,
    dual_impedance_required: true,
    show: true,
  },
  height: {
    order: 4,
    key: 'height',
    label: localize(`attributes.${'height: '}`),
    unit: ' cm',
    show: true,
  },
  age: {
    order: 5,
    key: 'age',
    label: localize(`attributes.${'age: '}`),
    unit: localize(`unit.${' years'}`),
    show: true,
  },
  gender: {
    order: 6,
    key: 'gender',
    label: localize(`attributes.${'gender: '}`),
    show: true,
  },
};

export const attributes_lb = {
  weight: {
    order: 1,
    key: 'weight',
    label: localize(`attributes.${'weight: '}`),
    show: true,
    unit: ' lbs',
    compute: compute.convertkgtolb,
  },
  impedance: {
    order: 2,
    key: 'impedance',
    label: localize(`attributes.${'impedance: '}`),
    show: true,
    unit: ' ohm',
    impedance_required: true,
  },
  impedance_low: {
    order: 2,
    key: 'impedance_low',
    label: localize(`attributes.${'impedance_low: '}`),
    show: true,
    unit: ' ohm',
    impedance_required: true,
    dual_impedance_required: true,
  },
  impedance_high: {
    order: 3,
    key: 'impedance_high',
    label: localize(`attributes.${'impedance_high: '}`),
    show: true,
    unit: ' ohm',
    impedance_required: true,
    dual_impedance_required: true,
  },
  height: {
    order: 4,
    key: 'height',
    label: localize(`attributes.${'height: '}`),
    unit: ' cm',
    show: true,
  },
  age: {
    order: 5,
    key: 'age',
    label: localize(`attributes.${'age: '}`),
    unit: localize(`unit.${' years'}`),
    show: true,
  },
  gender: {
    order: 6,
    key: 'gender',
    label: localize(`attributes.${'gender: '}`),
    show: true,
  },
};

export const body_kg: Record<string, RenderBodyData> = {
  basal_metabolism: {
    order: 1,
    key: 'basal_metabolism',
    label: localize(`body.${'basal_metabolism'}`),
    icon: 'basal_metabolism.png',
    unit: ' kcal',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 0, to: 1549, color: 'red', label: 'objective_not_achieved' },
      { from: 1549, to: 3000, color: 'green', label: 'objective_achieved' },
    ],
    impedance_required: false,
    show: true,
  },
  bcm: {
    order: 2,
    key: 'bcm',
    label: localize(`body.${'bcm'}`),
    icon: 'mdi:cellphone',
    unit: ' kg',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 0, to: 25, color: 'red', label: 'low' },
      { from: 25, to: 35, color: 'green', label: 'normal' },
      { from: 35, to: 50, color: 'blue', label: 'good' },
    ],
    impedance_required: true,
    dual_impedance_required: true,
    show: true,
  },
  bmi: {
    order: 3,
    key: 'bmi',
    label: localize(`body.${'bmi'}`),
    icon: 'bmi.png',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 12, to: 18.5, color: 'blue', label: 'low' },
      { from: 18.5, to: 25.0, color: 'green', label: 'normal' },
      { from: 25.0, to: 30.0, color: 'orange', label: 'high' },
      { from: 30.0, to: 36.5, color: 'red', label: 'very_high' },
    ],
    impedance_required: false,
    show: true,
  },
  bmi_label: {
    order: 4,
    key: 'bmi_label',
    label: localize(`body.${'bmi_label'}`),
    icon: 'body_type.png',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: null,
    showbelowlabels: null,
    severity: null,
    impedance_required: false,
    show: true,
  },
  body_fat: {
    order: 5,
    key: 'body_fat',
    label: localize(`body.${'body_fat'}`),
    icon: 'body_fat.png',
    unit: ' %',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 5, to: 12, color: 'royalblue', label: 'very_low' },
      { from: 12, to: 18, color: 'blue', label: 'low' },
      { from: 18, to: 23, color: 'green', label: 'normal' },
      { from: 23, to: 28, color: 'orange', label: 'increased' },
      { from: 28, to: 35, color: 'red', label: 'high' },
    ],
    impedance_required: true,
    show: true,
  },
  body_type: {
    order: 6,
    key: 'body_type',
    label: localize(`body.${'body_type'}`),
    icon: 'body_type.png',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: null,
    showbelowlabels: null,
    severity: null,
    impedance_required: true,
    show: true,
  },
  bone_mass: {
    order: 7,
    key: 'bone_mass',
    label: localize(`body.${'bone_mass'}`),
    icon: 'bone_mass.png',
    unit: ' kg',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 0, to: 2.00, color: 'red', label: 'insufficient' },
      { from: 2.00, to: 4.20, color: 'green', label: 'normal' },
      { from: 4.20, to: 6.40, color: 'blue', label: 'good' },
    ],
    impedance_required: true,
    show: true,
  },
  ecw_tbw_ratio: {
    order: 8,
    key: 'ecw_tbw_ratio',
    label: localize(`body.${'ecw_tbw_ratio'}`),
    icon: 'mdi:chart-pie',
    unit: ' %',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 0, to: 36, color: 'blue', label: 'low' },
      { from: 36, to: 41, color: 'green', label: 'normal' },
      { from: 41, to: 45, color: 'orange', label: 'high' },
      { from: 45, to: 60, color: 'red', label: 'very_high' },
    ],
    impedance_required: true,
    dual_impedance_required: true,
    show: true,
  },
  extracellular_water: {
    order: 9,
    key: 'extracellular_water',
    label: localize(`body.${'extracellular_water'}`),
    icon: 'mdi:water-opacity',
    unit: ' L',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 0, to: 14, color: 'blue', label: 'low' },
      { from: 14, to: 22, color: 'green', label: 'normal' },
      { from: 22, to: 28, color: 'orange', label: 'high' },
      { from: 28, to: 50, color: 'red', label: 'very_high' },
    ],
    impedance_required: true,
    dual_impedance_required: true,
    show: true,
  },
  ideal: {
    order: 10,
    key: 'ideal',
    label: localize(`body.${'ideal'}`),
    icon: 'ideal.png',
    unit: ' kg',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 39.30, to: 57.30, color: 'blue', label: 'underweight' },
      { from: 57.30, to: 75.30, color: 'green', label: 'balanced' },
      { from: 75.30, to: 93.30, color: 'orange', label: 'overweight' },
      { from: 93.30, to: 111.30, color: 'red', label: 'obese' },
    ],
    impedance_required: false,
    show: true,
  },
  intracellular_water: {
    order: 11,
    key: 'intracellular_water',
    label: localize(`body.${'intracellular_water'}`),
    icon: 'mdi:water-circle',
    unit: ' L',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 0, to: 18, color: 'blue', label: 'low' },
      { from: 18, to: 27, color: 'green', label: 'normal' },
      { from: 27, to: 33, color: 'orange', label: 'high' },
      { from: 33, to: 60, color: 'red', label: 'very_high' },
    ],
    impedance_required: true,
    dual_impedance_required: true,
    show: true,
  },
  metabolic_age: {
    order: 12,
    key: 'metabolic_age',
    label: localize(`body.${'metabolic_age'}`),
    icon: 'metabolic_age.png',
    unit: localize(`unit.${' years'}`),
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: null,
    showbelowlabels: null,
    severity: null,
    impedance_required: true,
    show: true,
  },
  muscle_mass: {
    order: 13,
    key: 'muscle_mass',
    label: localize(`body.${'muscle_mass'}`),
    icon: 'muscle_mass.png',
    unit: ' kg',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 39.30, to: 49.40, color: 'red', label: 'insufficient' },
      { from: 49.40, to: 59.50, color: 'green', label: 'normal' },
      { from: 59.50, to: 69.60, color: 'blue', label: 'good' },
    ],
    impedance_required: true,
    show: true,
  },
  protein: {
    order: 14,
    key: 'protein',
    label: localize(`body.${'protein'}`),
    icon: 'protein.png',
    unit: ' %',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 11, to: 16, color: 'red', label: 'insufficient' },
      { from: 16, to: 20, color: 'green', label: 'normal' },
      { from: 20, to: 24, color: 'blue', label: 'good' },
    ],
    impedance_required: true,
    show: true,
  },
  skeletal_muscle_mass: {
    order: 15,
    key: 'skeletal_muscle_mass',
    label: localize(`body.${'skeletal_muscle_mass'}`),
    icon: 'mdi:arm-flex',
    unit: ' kg',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 0, to: 29, color: 'red', label: 'low' },
      { from: 29, to: 35, color: 'orange', label: 'below_normal' },
      { from: 35, to: 44, color: 'green', label: 'normal' },
      { from: 44, to: 55, color: 'blue', label: 'good' },
    ],
    impedance_required: true,
    show: true,
    dual_impedance_required: true,
  },
  visceral_fat: {
    order: 16,
    key: 'visceral_fat',
    label: localize(`body.${'visceral_fat'}`),
    icon: 'visceral_fat.png',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 5, to: 10, color: 'green', label: 'normal' },
      { from: 10, to: 15, color: 'orange', label: 'high' },
      { from: 15, to: 20, color: 'red', label: 'very_high' },
    ],
    impedance_required: false,
    show: true,
  },
  water: {
    order: 17,
    key: 'water',
    label: localize(`body.${'water'}`),
    icon: 'water.png',
    unit: ' %',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 45, to: 55, color: 'red', label: 'insufficient' },
      { from: 55, to: 65.1, color: 'green', label: 'normal' },
      { from: 65.1, to: 75, color: 'blue', label: 'good' },
    ],
    impedance_required: true,
    show: true,
  },
  weight: {
    order: 18,
    key: 'weight',
    label: localize(`body.${'weight'}`),
    icon: 'ideal.png',
    unit: ' kg',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 39.30, to: 57.30, color: 'blue', label: 'underweight' },
      { from: 57.30, to: 75.30, color: 'green', label: 'balanced' },
      { from: 75.30, to: 93.30, color: 'orange', label: 'overweight' },
      { from: 93.30, to: 111.30, color: 'red', label: 'obese' },
    ],
    impedance_required: false,
    show: true,
  },
};
export const body_lb: Record<string, RenderBodyData> = {
  basal_metabolism: {
    order: 1,
    key: 'basal_metabolism',
    label: localize(`body.${'basal_metabolism'}`),
    icon: 'basal_metabolism.png',
    unit: ' kcal',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 0, to: 1549, color: 'red', label: 'objective_not_achieved' },
      { from: 1549, to: 3000, color: 'green', label: 'objective_achieved' },
    ],
    impedance_required: false,
    show: true,
  },
  bcm: {
    order: 2,
    key: 'bcm',
    label: localize(`body.${'bcm'}`),
    icon: 'mdi:cellphone',
    unit: ' lbs',
    compute: compute.convertkgtolb,
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 0, to: 55.11, color: 'red', label: 'low' },
      { from: 55.11, to: 77.11, color: 'green', label: 'normal' },
      { from: 77.11, to: 110.11, color: 'blue', label: 'good' },
    ],
    impedance_required: true,
    dual_impedance_required: true,
    show: true,
  },
  bmi: {
    order: 3,
    key: 'bmi',
    label: localize(`body.${'bmi'}`),
    icon: 'bmi.png',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 12, to: 18.5, color: 'blue', label: 'low' },
      { from: 18.5, to: 25.0, color: 'green', label: 'normal' },
      { from: 25.0, to: 30.0, color: 'orange', label: 'high' },
      { from: 30.0, to: 36.5, color: 'red', label: 'very_high' },
    ],
    impedance_required: false,
    show: true,
  },
  bmi_label: {
    order: 4,
    key: 'bmi_label',
    label: localize(`body.${'bmi_label'}`),
    icon: 'body_type.png',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: null,
    showbelowlabels: null,
    severity: null,
    impedance_required: false,
    show: true,
  },
  body_fat: {
    order: 5,
    key: 'body_fat',
    label: localize(`body.${'body_fat'}`),
    icon: 'body_fat.png',
    unit: ' %',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 5, to: 12, color: 'royalblue', label: 'very_low' },
      { from: 12, to: 18, color: 'blue', label: 'low' },
      { from: 18, to: 23, color: 'green', label: 'normal' },
      { from: 23, to: 28, color: 'orange', label: 'increased' },
      { from: 28, to: 35, color: 'red', label: 'high' },
    ],
    impedance_required: true,
    show: true,
  },
  body_type: {
    order: 6,
    key: 'body_type',
    label: localize(`body.${'body_type'}`),
    icon: 'body_type.png',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: null,
    showbelowlabels: null,
    severity: null,
    impedance_required: true,
    show: true,
  },
  bone_mass: {
    order: 7,
    key: 'bone_mass',
    label: localize(`body.${'bone_mass'}`),
    icon: 'bone_mass.png',
    unit: ' lbs',
    compute: compute.convertkgtolb,
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 0, to: 4.41, color: 'red', label: 'insufficient' },
      { from: 4.41, to: 9.26, color: 'green', label: 'normal' },
      { from: 9.26, to: 14.11, color: 'blue', label: 'good' },
    ],
    impedance_required: true,
    show: true,
  },
  ecw_tbw_ratio: {
    order: 8,
    key: 'ecw_tbw_ratio',
    label: localize(`body.${'ecw_tbw_ratio'}`),
    icon: 'mdi:chart-pie',
    unit: ' %',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 0, to: 36, color: 'blue', label: 'low' },
      { from: 36, to: 41, color: 'green', label: 'normal' },
      { from: 41, to: 45, color: 'orange', label: 'high' },
      { from: 45, to: 60, color: 'red', label: 'very_high' },
    ],
    impedance_required: true,
    dual_impedance_required: true,
    show: true,
  },
  extracellular_water: {
    order: 9,
    key: 'extracellular_water',
    label: localize(`body.${'extracellular_water'}`),
    icon: 'mdi:water-opacity',
    unit: ' L',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 0, to: 14, color: 'blue', label: 'low' },
      { from: 14, to: 22, color: 'green', label: 'normal' },
      { from: 22, to: 28, color: 'orange', label: 'high' },
      { from: 28, to: 50, color: 'red', label: 'very_high' },
    ],
    impedance_required: true,
    dual_impedance_required: true,
    show: true,
  },
  ideal: {
    order: 10,
    key: 'ideal',
    label: localize(`body.${'ideal'}`),
    icon: 'ideal.png',
    unit: ' lbs',
    compute: compute.convertkgtolb,
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 86.64, to: 126.34, color: 'blue', label: 'underweight' },
      { from: 126.34, to: 166.04, color: 'green', label: 'balanced' },
      { from: 166.04, to: 205.75, color: 'orange', label: 'overweight' },
      { from: 205.75, to: 245.45, color: 'red', label: 'obese' },
    ],
    impedance_required: false,
    show: true,
  },
  intracellular_water: {
    order: 11,
    key: 'intracellular_water',
    label: localize(`body.${'intracellular_water'}`),
    icon: 'mdi:water-circle',
    unit: ' L',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 0, to: 18, color: 'blue', label: 'low' },
      { from: 18, to: 27, color: 'green', label: 'normal' },
      { from: 27, to: 33, color: 'orange', label: 'high' },
      { from: 33, to: 60, color: 'red', label: 'very_high' },
    ],
    impedance_required: true,
    dual_impedance_required: true,
    show: true,
  },
  metabolic_age: {
    order: 12,
    key: 'metabolic_age',
    label: localize(`body.${'metabolic_age'}`),
    icon: 'metabolic_age.png',
    unit: localize(`unit.${' years'}`),
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: null,
    showbelowlabels: null,
    severity: null,
    impedance_required: true,
    show: true,
  },
  muscle_mass: {
    order: 13,
    key: 'muscle_mass',
    label: localize(`body.${'muscle_mass'}`),
    icon: 'muscle_mass.png',
    unit: ' lbs',
    compute: compute.convertkgtolb,
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 86.64, to: 108.97, color: 'red', label: 'insufficient' },
      { from: 108.97, to: 131.17, color: 'green', label: 'normal' },
      { from: 131.17, to: 153.38, color: 'blue', label: 'good' },
    ],
    impedance_required: true,
    show: true,
  },
  protein: {
    order: 14,
    key: 'protein',
    label: localize(`body.${'protein'}`),
    icon: 'protein.png',
    unit: ' %',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 11, to: 16, color: 'red', label: 'insufficient' },
      { from: 16, to: 20, color: 'green', label: 'normal' },
      { from: 20, to: 24, color: 'blue', label: 'good' },
    ],
    impedance_required: true,
    show: true,
  },
  skeletal_muscle_mass: {
    order: 15,
    key: 'skeletal_muscle_mass',
    label: localize(`body.${'skeletal_muscle_mass'}`),
    icon: 'mdi:arm-flex',
    unit: ' lbs',
    compute: compute.convertkgtolb,
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 0, to: 63.93, color: 'red', label: 'low' },
      { from: 63.93, to: 77.16, color: 'orange', label: 'below_normal' },
      { from: 77.16, to: 97.70, color: 'green', label: 'normal' },
      { from: 97.70, to: 121.13, color: 'blue', label: 'good' },
    ],
    impedance_required: true,
    dual_impedance_required: true,
    show: true,
  },
  visceral_fat: {
    order: 16,
    key: 'visceral_fat',
    label: localize(`body.${'visceral_fat'}`),
    icon: 'visceral_fat.png',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 5, to: 10, color: 'green', label: 'normal' },
      { from: 10, to: 15, color: 'orange', label: 'high' },
      { from: 15, to: 20, color: 'red', label: 'very_high' },
    ],
    impedance_required: false,
    show: true,
  },
  water: {
    order: 17,
    key: 'water',
    label: localize(`body.${'water'}`),
    icon: 'water.png',
    unit: ' %',
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 45, to: 55, color: 'red', label: 'insufficient' },
      { from: 55, to: 65.1, color: 'green', label: 'normal' },
      { from: 65.1, to: 75, color: 'blue', label: 'good' },
    ],
    impedance_required: true,
    show: true,
  },
  weight: {
    order: 18,
    key: 'weight',
    label: localize(`body.${'weight'}`),
    icon: 'ideal.png',
    unit: ' lbs',
    compute: compute.convertkgtolb,
    color: 'var(--score-card-color, var(--ha-card-background))',
    positions: {
      icon: 'left',
      name: 'left',
      minmax: 'off',
      value: 'right',
    },
    showabovelabels: "true",
    showbelowlabels: "true",
    severity: [
      { from: 86.64, to: 126.34, color: 'blue', label: 'underweight' },
      { from: 126.34, to: 166.04, color: 'green', label: 'balanced' },
      { from: 166.04, to: 205.75, color: 'orange', label: 'overweight' },
      { from: 205.75, to: 245.45, color: 'red', label: 'obese' },
    ],
    impedance_required: false,
    show: true,
  },
};

export const buttons = {
  user1: {
    show: false,
    label: 'User1',
    icon: 'mdi:alpha-u-circle',
    entity: '',
  },
  user2: {
    show: false,
    label: 'User2',
    icon: 'mdi:alpha-u-circle',
    entity: '',
  },
  user3: {
    show: false,
    label: 'User3',
    icon: 'mdi:alpha-u-circle',
    entity: '',
  },
  user4: {
    show: false,
    label: 'User4',
    icon: 'mdi:alpha-u-circle',
    entity: '',
  },
  user5: {
    show: false,
    label: 'User5',
    icon: 'mdi:alpha-u-circle',
    entity: '',
  },
};

export const defaultCardConfig: Partial<BodymiscaleCardConfig> = {
  model: false,
  dual_impedance: false,
  unit: false,
  theme: true,
  show_name: true,
  show_states: true,
  show_attributes: true,
  show_always_details: false,
  show_toolbar: true,
  show_body: true,
  show_buttons: false,
  attributes: {
    weight: {
      order: 1,
      key: 'weight',
      show: true,
    },
    impedance: {
      order: 2,
      key: 'impedance',
      impedance_required: true,
      dual_impedance_required: false,
      show: true,
    },
    impedance_low: {
      order: 2,
      key: 'impedance_low',
      impedance_required: true,
      dual_impedance_required: true,
      show: true,
    },
    impedance_high: {
      order: 3,
      key: 'impedance_high',
      impedance_required: true,
      dual_impedance_required: true,
      show: true,
    },
    height: {
      order: 4,
      key: 'height',
      show: true,
    },
    age: {
      order: 5,
      key: 'age',
      show: true,
    },
    gender: {
      order: 6,
      key: 'gender',
      show: true,
    },
  },
  body: {
    basal_metabolism: {
      order: 1,
      key: 'basal_metabolism',
      severity: [
        { from: 0, to: 1549, color: 'red', label: 'objective_not_achieved' },
        { from: 1549, to: 3000, color: 'green', label: 'objective_achieved' },
      ],
      show: true,
      impedance_required: false,
    },
    bcm: {
      order: 2,
      key: 'bcm',
      severity: [
        { from: 0, to: 25, color: 'red', label: 'low' },
        { from: 25, to: 35, color: 'green', label: 'normal' },
        { from: 35, to: 50, color: 'blue', label: 'good' },
      ],
      show: true,
      impedance_required: true,
      dual_impedance_required: true,
    },
    bmi: {
      order: 3,
      key: 'bmi',
      severity: [
        { from: 12, to: 18.5, color: 'blue', label: 'low' },
        { from: 18.5, to: 25.0, color: 'green', label: 'normal' },
        { from: 25.0, to: 30.0, color: 'orange', label: 'high' },
        { from: 30.0, to: 36.5, color: 'red', label: 'very_high' },
      ],
      show: true,
      impedance_required: false,
    },
    bmi_label: {
      order: 4,
      key: 'bmi_label',
      show: true,
      impedance_required: false,
    },
    body_fat: {
      order: 5,
      key: 'body_fat',
      severity: [
        { from: 5, to: 12, color: 'royalblue', label: 'very_low' },
        { from: 12, to: 18, color: 'blue', label: 'low' },
        { from: 18, to: 23, color: 'green', label: 'normal' },
        { from: 23, to: 28, color: 'orange', label: 'increased' },
        { from: 28, to: 35, color: 'red', label: 'high' },
      ],
      show: true,
      impedance_required: true,
    },
    body_type: {
      order: 6,
      key: 'body_type',
      show: true,
      impedance_required: true,
    },
    bone_mass: {
      order: 7,
      key: 'bone_mass',
      severity: [
        { from: 0, to: 2.00, color: 'red', label: 'insufficient' },
        { from: 2.00, to: 4.20, color: 'green', label: 'normal' },
        { from: 4.20, to: 6.40, color: 'blue', label: 'good' },
      ],
      show: true,
      impedance_required: true,
    },
    ecw_tbw_ratio: {
      order: 8,
      key: 'ecw_tbw_ratio',
      severity: [
        { from: 0, to: 36, color: 'blue', label: 'low' },
        { from: 36, to: 41, color: 'green', label: 'normal' },
        { from: 41, to: 45, color: 'orange', label: 'high' },
        { from: 45, to: 60, color: 'red', label: 'very_high' },
      ],
      impedance_required: true,
      dual_impedance_required: true,
      show: true,
    },
    extracellular_water: {
      order: 9,
      key: 'extracellular_water',
      severity: [
        { from: 0, to: 14, color: 'blue', label: 'low' },
        { from: 14, to: 22, color: 'green', label: 'normal' },
        { from: 22, to: 28, color: 'orange', label: 'high' },
        { from: 28, to: 50, color: 'red', label: 'very_high' },
      ],
      impedance_required: true,
      dual_impedance_required: true,
      show: true,
    },
    ideal: {
      order: 10,
      key: 'ideal',
      severity: [
        { from: 39.30, to: 57.30, color: 'blue', label: 'underweight' },
        { from: 57.30, to: 75.30, color: 'green', label: 'balanced' },
        { from: 75.30, to: 93.30, color: 'orange', label: 'overweight' },
        { from: 93.30, to: 111.30, color: 'red', label: 'obese' },
      ],
      impedance_required: false,
      show: true,
    },
    intracellular_water: {
      order: 11,
      key: 'intracellular_water',
      severity: [
        { from: 0, to: 18, color: 'blue', label: 'low' },
        { from: 18, to: 27, color: 'green', label: 'normal' },
        { from: 27, to: 33, color: 'orange', label: 'high' },
        { from: 33, to: 60, color: 'red', label: 'very_high' },
      ],
      impedance_required: true,
      dual_impedance_required: true,
      show: true,
    },
    metabolic_age: {
      order: 12,
      key: 'metabolic_age',
      impedance_required: true,
      show: true,
    },
    muscle_mass: {
      order: 13,
      key: 'muscle_mass',
      severity: [
        { from: 39.30, to: 49.40, color: 'red', label: 'insufficient' },
        { from: 49.40, to: 59.50, color: 'green', label: 'normal' },
        { from: 59.50, to: 69.60, color: 'blue', label: 'good' },
      ],
      impedance_required: true,
      show: true,
    },
    protein: {
      order: 14,
      key: 'protein',
      severity: [
        { from: 11, to: 16, color: 'red', label: 'insufficient' },
        { from: 16, to: 20, color: 'green', label: 'normal' },
        { from: 20, to: 24, color: 'blue', label: 'good' },
      ],
      impedance_required: true,
      show: true,
    },
    skeletal_muscle_mass: {
      order: 15,
      key: 'skeletal_muscle_mass',
      severity: [
        { from: 0, to: 29, color: 'red', label: 'low' },
        { from: 29, to: 35, color: 'orange', label: 'below_normal' },
        { from: 35, to: 44, color: 'green', label: 'normal' },
        { from: 44, to: 55, color: 'blue', label: 'good' },
      ],
      impedance_required: true,
      dual_impedance_required: true,
      show: true,
    },
    visceral_fat: {
      order: 16,
      key: 'visceral_fat',
      severity: [
        { from: 5, to: 10, color: 'green', label: 'normal' },
        { from: 10, to: 15, color: 'orange', label: 'high' },
        { from: 15, to: 20, color: 'red', label: 'very_high' },
      ],
      impedance_required: false,
      show: true,
    },
    water: {
      order: 17,
      key: 'water',
      severity: [
        { from: 45, to: 55, color: 'red', label: 'insufficient' },
        { from: 55, to: 65.1, color: 'green', label: 'normal' },
        { from: 65.1, to: 75, color: 'blue', label: 'good' },
      ],
      impedance_required: true,
      show: true,
    },
    weight: {
      order: 18,
      key: 'weight',
      severity: [
        { from: 39.30, to: 57.30, color: 'blue', label: 'underweight' },
        { from: 57.30, to: 75.30, color: 'green', label: 'balanced' },
        { from: 75.30, to: 93.30, color: 'orange', label: 'overweight' },
        { from: 93.30, to: 111.30, color: 'red', label: 'obese' },
      ],
      impedance_required: false,
      show: true,
    },
  },
};

